# Wrangling Project
## Cleaning Baseball Reference Dataframe
#### Drew Peterson
***

In [23]:
#Imports
import pandas as pd

In [24]:
#Read and display raw csv file
br = pd.read_csv("BaseballReference.csv")

display(br)

,Rk,Tm,W,L,W-L%,R,RA,Rdiff,SOS,SRS,...,vWest,Inter,Home,Road,ExInn,1Run,vRHP,vLHP,≥.500,<.500
0,1.0,Milwaukee Brewers,97,65,0.599,5.0,3.9,1.1,0.0,1.0,...,17-15,28-20,52-29,45-36,7-5,28-20,68-47,29-18,46-38,51-27
1,2.0,Philadelphia Phillies,96,66,0.593,4.8,4.0,0.8,-0.1,0.7,...,20-12,31-17,55-26,41-40,9-6,26-21,73-41,23-25,45-35,51-31
2,3.0,Toronto Blue Jays,94,68,0.580,4.9,4.5,0.5,0.1,0.5,...,19-12,30-18,54-27,40-41,10-4,27-20,70-52,24-16,49-41,45-27
3,4.0,New York Yankees,94,68,0.580,5.2,4.2,1.0,0.0,1.0,...,20-11,26-22,50-31,44-37,6-8,23-22,75-51,19-17,45-44,49-24
4,5.0,Los Angeles Dodgers,93,69,0.574,5.1,4.2,0.9,-0.1,0.7,...,36-16,27-21,52-29,41-40,8-7,25-24,69-46,24-23,48-37,45-32
5,6.0,Chicago Cubs,92,70,0.568,4.9,4.0,0.9,0.0,0.9,...,17-15,30-18,50-31,42-39,6-5,25-19,73-47,19-23,38-46,54-24
6,7.0,Seattle Mariners,90,72,0.556,4.7,4.3,0.4,0.0,0.4,...,34-18,25-23,51-30,39-42,10-11,31-22,63-52,27-20,47-43,43-29
7,8.0,San Diego Padres,90,72,0.556,4.3,3.8,0.5,-0.1,0.4,...,32-20,20-28,52-29,38-43,8-4,30-23,64-49,26-23,43-43,47-29
8,9.0,Boston Red Sox,89,73,0.549,4.9,4.2,0.7,0.0,0.7,...,14-17,26-22,48-33,41-40,8-12,23-27,65-52,24-21,44-43,45-30
9,10.0,Cleveland Guardians,88,74,0.543,4.0,4.0,0.0,0.0,0.0,...,15-15,20-28,45-36,43-38,12-6,26-20,66-50,22-24,42-47,46-27
10,11.0,Houston Astros,87,75,0.537,4.2,4.1,0.1,-0.1,0.1,...,25-27,31-17,46-35,41-40,8-7,27-17,68-61,19-14,43-43,44-32
11,12.0,Detroit Tigers,87,75,0.537,4.7,4.3,0.4,-0.1,0.4,...,15-16,23-25,46-35,41-40,5-8,21-12,62-58,25-17,44-43,43-32
12,13.0,New York Mets,83,79,0.512,4.7,4.4,0.3,-0.1,0.3,...,19-12,24-24,49-32,34-47,6-7,23-26,58-57,25-22,40-40,43-39
13,14.0,Cincinnati Reds,83,79,0.512,4.4,4.2,0.2,0.0,0.2,...,17-13,26-22,45-36,38-43,3-12,22-22,62-54,21-25,44-42,39-37
14,15.0,Kansas City Royals,82,80,0.506,4.0,3.9,0.1,0.0,0.1,...,17-15,26-22,43-38,39-42,7-5,24-20,62-67,20-13,37-51,45-29
15,16.0,San Francisco Giants,81,81,0.500,4.4,4.2,0.1,-0.1,0.1,...,24-28,24-24,42-39,39-42,9-6,28-30,64-53,17-28,40-45,41-36
16,17.0,Texas Rangers,81,81,0.500,4.2,3.7,0.5,0.0,0.5,...,25-27,25-23,48-33,33-48,9-8,21-29,64-57,17-24,37-51,44-30
17,18.0,Arizona Diamondbacks,80,82,0.494,4.9,4.8,0.0,-0.1,0.0,...,26-26,25-23,43-38,37-44,7-12,21-28,59-57,21-25,48-53,32-29
18,19.0,Miami Marlins,79,83,0.488,4.4,4.9,-0.5,0.0,-0.6,...,14-16,26-22,38-43,41-40,10-4,22-22,58-57,21-26,43-47,36-36
19,20.0,St. Louis Cardinals,78,84,0.481,4.3,4.7,-0.4,0.1,-0.3,...,16-15,22-26,44-37,34-47,4-8,26-21,54-62,24-22,45-56,33-28
20,21.0,Tampa Bay Rays,77,85,0.475,4.4,4.2,0.2,0.1,0.3,...,16-15,28-20,41-40,36-45,5-7,22-29,57-58,20-27,44-57,33-28
21,22.0,Athletics,76,86,0.469,4.5,5.0,-0.5,0.0,-0.5,...,23-29,20-28,36-45,40-41,9-5,20-21,55-68,21-18,45-58,31-28
22,23.0,Atlanta Braves,76,86,0.469,4.5,4.5,-0.1,0.0,-0.1,...,9-22,22-26,39-42,37-44,8-8,21-35,53-67,23-19,39-55,37-31
23,24.0,Baltimore Orioles,75,87,0.463,4.2,4.9,-0.7,0.1,-0.6,...,17-14,24-24,39-42,36-45,6-6,27-24,53-62,22-25,43-58,32-29
24,25.0,Los Angeles Angels,72,90,0.444,4.2,5.2,-1.0,0.1,-0.9,...,23-29,22-26,39-42,33-48,9-5,28-21,61-73,11-17,44-60,28-30
25,26.0,Pittsburgh Pirates,71,91,0.438,3.6,4.0,-0.4,0.1,-0.3,...,17-13,17-31,44-37,27-54,7-7,25-35,56-70,15-21,39-60,32-31
26,27.0,Minnesota Twins,70,92,0.432,4.2,4.8,-0.6,0.0,-0.5,...,14-18,20-28,38-43,32-49,4-11,15-27,57-69,13-23,43-60,27-32
27,28.0,Washington Nationals,66,96,0.407,4.2,5.5,-1.3,0.0,-1.3,...,15-16,19-29,32-49,34-47,5-3,24-18,48-66,18-30,34-55,32-41
28,29.0,Chicago White Sox,60,102,0.370,4.0,4.6,-0.6,0.1,-0.5,...,10-20,21-27,33-48,27-54,3-7,15-36,45-79,15-23,33-71,27-31
29,30.0,Colorado Rockies,43,119,0.265,3.7,6.3,-2.6,0.1,-2.5,...,12-40,12-36,25-56,18-63,1-5,18-23,35-85,8-34,15-85,28-34
30,NaN,Average,81,81,0.500,4.5,4.4,NaN,NaN,NaN,...,19-18,24-24,43-37,37-43,6-6,23-23,60-58,20-22,41-50,39-30

In [25]:
#Takes only the columns needed for my analysis
cleaned_br = br[["Rk", "Tm", "W", "L", "RA"]]
cleaned_br = cleaned_br.iloc[:-1]
#Drops index 30 "averages" row
display(cleaned_br)

      Rk                     Tm   W    L   RA
0    1.0      Milwaukee Brewers  97   65  3.9
1    2.0  Philadelphia Phillies  96   66  4.0
2    3.0      Toronto Blue Jays  94   68  4.5
3    4.0       New York Yankees  94   68  4.2
4    5.0    Los Angeles Dodgers  93   69  4.2
5    6.0           Chicago Cubs  92   70  4.0
6    7.0       Seattle Mariners  90   72  4.3
7    8.0       San Diego Padres  90   72  3.8
8    9.0         Boston Red Sox  89   73  4.2
9   10.0    Cleveland Guardians  88   74  4.0
10  11.0         Houston Astros  87   75  4.1
11  12.0         Detroit Tigers  87   75  4.3
12  13.0          New York Mets  83   79  4.4
13  14.0        Cincinnati Reds  83   79  4.2
14  15.0     Kansas City Royals  82   80  3.9
15  16.0   San Francisco Giants  81   81  4.2
16  17.0          Texas Rangers  81   81  3.7
17  18.0   Arizona Diamondbacks  80   82  4.8
18  19.0          Miami Marlins  79   83  4.9
19  20.0    St. Louis Cardinals  78   84  4.7
20  21.0         Tampa Bay Rays  77   85  4.2
21  22.0              Athletics  76   86  5.0
22  23.0         Atlanta Braves  76   86  4.5
23  24.0      Baltimore Orioles  75   87  4.9
24  25.0     Los Angeles Angels  72   90  5.2
25  26.0     Pittsburgh Pirates  71   91  4.0
26  27.0        Minnesota Twins  70   92  4.8
27  28.0   Washington Nationals  66   96  5.5
28  29.0      Chicago White Sox  60  102  4.6
29  30.0       Colorado Rockies  43  119  6.3

In [26]:
cleaned_br["Rk"] = cleaned_br["Rk"].astype(int)
cleaned_br = cleaned_br
cleaned_br.dtypes
display(cleaned_br)

    Rk                     Tm   W    L   RA
0    1      Milwaukee Brewers  97   65  3.9
1    2  Philadelphia Phillies  96   66  4.0
2    3      Toronto Blue Jays  94   68  4.5
3    4       New York Yankees  94   68  4.2
4    5    Los Angeles Dodgers  93   69  4.2
5    6           Chicago Cubs  92   70  4.0
6    7       Seattle Mariners  90   72  4.3
7    8       San Diego Padres  90   72  3.8
8    9         Boston Red Sox  89   73  4.2
9   10    Cleveland Guardians  88   74  4.0
10  11         Houston Astros  87   75  4.1
11  12         Detroit Tigers  87   75  4.3
12  13          New York Mets  83   79  4.4
13  14        Cincinnati Reds  83   79  4.2
14  15     Kansas City Royals  82   80  3.9
15  16   San Francisco Giants  81   81  4.2
16  17          Texas Rangers  81   81  3.7
17  18   Arizona Diamondbacks  80   82  4.8
18  19          Miami Marlins  79   83  4.9
19  20    St. Louis Cardinals  78   84  4.7
20  21         Tampa Bay Rays  77   85  4.2
21  22              Athletics  76   86  5.0
22  23         Atlanta Braves  76   86  4.5
23  24      Baltimore Orioles  75   87  4.9
24  25     Los Angeles Angels  72   90  5.2
25  26     Pittsburgh Pirates  71   91  4.0
26  27        Minnesota Twins  70   92  4.8
27  28   Washington Nationals  66   96  5.5
28  29      Chicago White Sox  60  102  4.6
29  30       Colorado Rockies  43  119  6.3

In [27]:
#Rename columns for better readibility
cleaned_br = cleaned_br.rename(columns={
    "Rk":"Rank",
    "Tm":"Team Name",
    "W":"Wins",
    "L":"Losses",
    "RA":"Runs Allowed"
})

display(cleaned_br)

    Rank              Team Name  Wins  Losses  Runs Allowed
0      1      Milwaukee Brewers    97      65           3.9
1      2  Philadelphia Phillies    96      66           4.0
2      3      Toronto Blue Jays    94      68           4.5
3      4       New York Yankees    94      68           4.2
4      5    Los Angeles Dodgers    93      69           4.2
5      6           Chicago Cubs    92      70           4.0
6      7       Seattle Mariners    90      72           4.3
7      8       San Diego Padres    90      72           3.8
8      9         Boston Red Sox    89      73           4.2
9     10    Cleveland Guardians    88      74           4.0
10    11         Houston Astros    87      75           4.1
11    12         Detroit Tigers    87      75           4.3
12    13          New York Mets    83      79           4.4
13    14        Cincinnati Reds    83      79           4.2
14    15     Kansas City Royals    82      80           3.9
15    16   San Francisco Giants    81      81           4.2
16    17          Texas Rangers    81      81           3.7
17    18   Arizona Diamondbacks    80      82           4.8
18    19          Miami Marlins    79      83           4.9
19    20    St. Louis Cardinals    78      84           4.7
20    21         Tampa Bay Rays    77      85           4.2
21    22              Athletics    76      86           5.0
22    23         Atlanta Braves    76      86           4.5
23    24      Baltimore Orioles    75      87           4.9
24    25     Los Angeles Angels    72      90           5.2
25    26     Pittsburgh Pirates    71      91           4.0
26    27        Minnesota Twins    70      92           4.8
27    28   Washington Nationals    66      96           5.5
28    29      Chicago White Sox    60     102           4.6
29    30       Colorado Rockies    43     119           6.3

In [28]:
#Writes file into csv 
cleaned_br.to_csv("Baseball_Reference_Cleaned.csv")