# Wrangling Project
## Scrapping Spotrac Data
#### Drew Peterson
***

In [15]:
#Imports
import pandas as pd
import requests

In [16]:
#Scrapes data using requests package and html_
url = "https://www.spotrac.com/mlb/cash/_/year/2025"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
html = response.text

#Parses tables
tables = pd.read_html(html)

spotrac_df = tables[0]

display(spotrac_df)

/var/folders/x5/cndptcpn0bngcgpkcg_sbzkr0000gn/T/ipykernel_20724/118092272.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

,Rank,Team,Record,Signed,Avg Age Team,Active,Retained,Total Cash
0,1.0,NYM NYM,83-79,28.0,29.3,"$312,899,806",$0,"$400,965,292"
1,2.0,LAD LAD,93-69,27.0,29.6,"$293,126,821",$0,"$393,082,178"
2,3.0,NYY NYY,94-68,28.0,29.7,"$205,097,386","$5,000,000","$323,561,450"
3,4.0,PHI PHI,96-66,27.0,30.3,"$226,300,409","$3,000,000","$308,208,429"
4,5.0,TOR TOR,94-68,28.0,28.9,"$179,210,208",$0,"$290,944,111"
5,6.0,HOU HOU,87-75,28.0,28.6,"$135,180,023","$701,520","$253,425,770"
6,7.0,TEX TEX,81-81,29.0,30.1,"$113,977,024",$0,"$251,697,316"
7,8.0,ATL ATL,76-86,28.0,29.5,"$128,648,209","$3,500,000","$237,076,106"
8,9.0,SD SD,90-72,28.0,29.3,"$160,473,830","$6,300,000","$236,031,133"
9,10.0,CHC CHC,92-70,28.0,29.6,"$173,037,007","$2,750,000","$231,356,720"
10,11.0,LAA LAA,72-90,28.0,27.5,"$97,348,952","$2,000,000","$230,062,125"
11,12.0,BOS BOS,89-73,28.0,28.8,"$122,765,355","$7,360,000","$229,129,601"
12,13.0,ARI ARI,80-82,28.0,27.4,"$73,085,886","$1,500,000","$204,349,736"
13,14.0,SF SF,81-81,28.0,28.4,"$142,688,005","$250,000","$200,678,481"
14,15.0,BAL BAL,75-87,28.0,27.3,"$64,226,457",$0,"$196,376,385"
15,16.0,SEA SEA,90-72,28.0,28.0,"$131,472,218","$1,750,000","$193,414,894"
16,17.0,DET DET,87-75,28.0,28.5,"$106,720,780","$2,000,000","$178,924,844"
17,18.0,STL STL,78-84,28.0,27.1,"$85,089,836",$0,"$153,377,987"
18,19.0,KC KC,82-80,28.0,28.5,"$85,396,877","$1,500,000","$153,094,633"
19,20.0,MIN MIN,70-92,28.0,27.8,"$49,208,783","$225,000","$150,415,875"
20,21.0,COL COL,43-119,28.0,26.0,"$60,303,466","$1,500,000","$149,531,167"
21,22.0,WSH WSH,66-96,28.0,26.1,"$25,294,554",$0,"$149,257,229"
22,23.0,MIL MIL,97-65,28.0,27.4,"$84,095,680","$600,000","$140,266,827"
23,24.0,CIN CIN,83-79,28.0,27.6,"$81,066,742","$3,000,000","$135,790,853"
24,25.0,CLE CLE,88-74,28.0,26.3,"$50,354,620",$0,"$118,369,450"
25,26.0,ATH ATH,76-86,28.0,26.9,"$64,911,684",$0,"$113,857,137"
26,27.0,PIT PIT,71-91,30.0,27.3,"$51,549,367",$0,"$104,739,138"
27,28.0,TB TB,77-85,28.0,28.0,"$41,355,049","$1,000,000","$102,798,243"
28,29.0,CHW CHW,60-102,28.0,26.4,"$17,295,751","$1,504,667","$101,146,763"
29,30.0,MIA MIA,79-83,28.0,26.3,"$33,912,751",$0,"$90,652,027"
30,NaN,Totals,-,841.0,-,"$3,396,093,536","$45,441,187","$6,022,581,900"
31,NaN,Averages,-,28.0,28.1,"$113,203,118","$1,514,706","$200,752,730"

In [17]:
#Selects columns that I want to keep
spotrac_cleaned = spotrac_df[["Team", "Active", "Total Cash"]]
display(spotrac_cleaned)

        Team          Active      Total Cash
0   NYM  NYM    $312,899,806    $400,965,292
1   LAD  LAD    $293,126,821    $393,082,178
2   NYY  NYY    $205,097,386    $323,561,450
3   PHI  PHI    $226,300,409    $308,208,429
4   TOR  TOR    $179,210,208    $290,944,111
5   HOU  HOU    $135,180,023    $253,425,770
6   TEX  TEX    $113,977,024    $251,697,316
7   ATL  ATL    $128,648,209    $237,076,106
8     SD  SD    $160,473,830    $236,031,133
9   CHC  CHC    $173,037,007    $231,356,720
10  LAA  LAA     $97,348,952    $230,062,125
11  BOS  BOS    $122,765,355    $229,129,601
12  ARI  ARI     $73,085,886    $204,349,736
13    SF  SF    $142,688,005    $200,678,481
14  BAL  BAL     $64,226,457    $196,376,385
15  SEA  SEA    $131,472,218    $193,414,894
16  DET  DET    $106,720,780    $178,924,844
17  STL  STL     $85,089,836    $153,377,987
18    KC  KC     $85,396,877    $153,094,633
19  MIN  MIN     $49,208,783    $150,415,875
20  COL  COL     $60,303,466    $149,531,167
21  WSH  WSH     $25,294,554    $149,257,229
22  MIL  MIL     $84,095,680    $140,266,827
23  CIN  CIN     $81,066,742    $135,790,853
24  CLE  CLE     $50,354,620    $118,369,450
25  ATH  ATH     $64,911,684    $113,857,137
26  PIT  PIT     $51,549,367    $104,739,138
27    TB  TB     $41,355,049    $102,798,243
28  CHW  CHW     $17,295,751    $101,146,763
29  MIA  MIA     $33,912,751     $90,652,027
30    Totals  $3,396,093,536  $6,022,581,900
31  Averages    $113,203,118    $200,752,730

In [18]:
#Drops rows 30 and 31
spotrac_cleaned = spotrac_cleaned.iloc[:-2]
display(spotrac_cleaned)

        Team        Active    Total Cash
0   NYM  NYM  $312,899,806  $400,965,292
1   LAD  LAD  $293,126,821  $393,082,178
2   NYY  NYY  $205,097,386  $323,561,450
3   PHI  PHI  $226,300,409  $308,208,429
4   TOR  TOR  $179,210,208  $290,944,111
5   HOU  HOU  $135,180,023  $253,425,770
6   TEX  TEX  $113,977,024  $251,697,316
7   ATL  ATL  $128,648,209  $237,076,106
8     SD  SD  $160,473,830  $236,031,133
9   CHC  CHC  $173,037,007  $231,356,720
10  LAA  LAA   $97,348,952  $230,062,125
11  BOS  BOS  $122,765,355  $229,129,601
12  ARI  ARI   $73,085,886  $204,349,736
13    SF  SF  $142,688,005  $200,678,481
14  BAL  BAL   $64,226,457  $196,376,385
15  SEA  SEA  $131,472,218  $193,414,894
16  DET  DET  $106,720,780  $178,924,844
17  STL  STL   $85,089,836  $153,377,987
18    KC  KC   $85,396,877  $153,094,633
19  MIN  MIN   $49,208,783  $150,415,875
20  COL  COL   $60,303,466  $149,531,167
21  WSH  WSH   $25,294,554  $149,257,229
22  MIL  MIL   $84,095,680  $140,266,827
23  CIN  CIN   $81,066,742  $135,790,853
24  CLE  CLE   $50,354,620  $118,369,450
25  ATH  ATH   $64,911,684  $113,857,137
26  PIT  PIT   $51,549,367  $104,739,138
27    TB  TB   $41,355,049  $102,798,243
28  CHW  CHW   $17,295,751  $101,146,763
29  MIA  MIA   $33,912,751   $90,652,027

In [19]:
#Cleans Team abbreviation column
spotrac_cleaned["Team"] = spotrac_cleaned["Team"].str.split().str[0]

#Removes $ sign from Active and Total Cash columns
cols = ["Active", "Total Cash"]

for col in cols:
    spotrac_cleaned[col] = (
        spotrac_cleaned[col]
        .replace(r"[\$,]", "", regex=True)
        .astype(float)
    )
print(spotrac_cleaned.dtypes)
display(spotrac_cleaned)

Team           object
Active        float64
Total Cash    float64
dtype: object

   Team       Active   Total Cash
0   NYM  312899806.0  400965292.0
1   LAD  293126821.0  393082178.0
2   NYY  205097386.0  323561450.0
3   PHI  226300409.0  308208429.0
4   TOR  179210208.0  290944111.0
5   HOU  135180023.0  253425770.0
6   TEX  113977024.0  251697316.0
7   ATL  128648209.0  237076106.0
8    SD  160473830.0  236031133.0
9   CHC  173037007.0  231356720.0
10  LAA   97348952.0  230062125.0
11  BOS  122765355.0  229129601.0
12  ARI   73085886.0  204349736.0
13   SF  142688005.0  200678481.0
14  BAL   64226457.0  196376385.0
15  SEA  131472218.0  193414894.0
16  DET  106720780.0  178924844.0
17  STL   85089836.0  153377987.0
18   KC   85396877.0  153094633.0
19  MIN   49208783.0  150415875.0
20  COL   60303466.0  149531167.0
21  WSH   25294554.0  149257229.0
22  MIL   84095680.0  140266827.0
23  CIN   81066742.0  135790853.0
24  CLE   50354620.0  118369450.0
25  ATH   64911684.0  113857137.0
26  PIT   51549367.0  104739138.0
27   TB   41355049.0  102798243.0
28  CHW   17295751.0  101146763.0
29  MIA   33912751.0   90652027.0

In [20]:
#Reads Baseball_Reference_Cleaned.csv, created in different notebook
br_df = pd.read_csv("Baseball_Reference_Cleaned.csv", index_col=0)
display(br_df)

    Rank              Team Name  Wins  Losses  Runs Allowed
0      1      Milwaukee Brewers    97      65           3.9
1      2  Philadelphia Phillies    96      66           4.0
2      3      Toronto Blue Jays    94      68           4.5
3      4       New York Yankees    94      68           4.2
4      5    Los Angeles Dodgers    93      69           4.2
5      6           Chicago Cubs    92      70           4.0
6      7       Seattle Mariners    90      72           4.3
7      8       San Diego Padres    90      72           3.8
8      9         Boston Red Sox    89      73           4.2
9     10    Cleveland Guardians    88      74           4.0
10    11         Houston Astros    87      75           4.1
11    12         Detroit Tigers    87      75           4.3
12    13          New York Mets    83      79           4.4
13    14        Cincinnati Reds    83      79           4.2
14    15     Kansas City Royals    82      80           3.9
15    16   San Francisco Giants    81      81           4.2
16    17          Texas Rangers    81      81           3.7
17    18   Arizona Diamondbacks    80      82           4.8
18    19          Miami Marlins    79      83           4.9
19    20    St. Louis Cardinals    78      84           4.7
20    21         Tampa Bay Rays    77      85           4.2
21    22              Athletics    76      86           5.0
22    23         Atlanta Braves    76      86           4.5
23    24      Baltimore Orioles    75      87           4.9
24    25     Los Angeles Angels    72      90           5.2
25    26     Pittsburgh Pirates    71      91           4.0
26    27        Minnesota Twins    70      92           4.8
27    28   Washington Nationals    66      96           5.5
28    29      Chicago White Sox    60     102           4.6
29    30       Colorado Rockies    43     119           6.3

In [21]:
#maps Team abbreviation column named Team for Baseball Reference dataframe
team_map = {
    "Milwaukee Brewers": "MIL",
    "Philadelphia Phillies": "PHI",
    "Toronto Blue Jays": "TOR",
    "New York Yankees": "NYY",
    "Los Angeles Dodgers": "LAD",
    "Chicago Cubs": "CHC",
    "Seattle Mariners": "SEA",
    "San Diego Padres": "SD",
    "Boston Red Sox": "BOS",
    "Cleveland Guardians": "CLE",
    "Houston Astros": "HOU",
    "Detroit Tigers": "DET",
    "New York Mets": "NYM",
    "Cincinnati Reds": "CIN",
    "Kansas City Royals": "KC",
    "San Francisco Giants": "SF",
    "Texas Rangers": "TEX",
    "Arizona Diamondbacks": "ARI",
    "Miami Marlins": "MIA",
    "St. Louis Cardinals": "STL",
    "Tampa Bay Rays": "TB",
    "Athletics": "ATH",
    "Atlanta Braves": "ATL",
    "Baltimore Orioles": "BAL",
    "Los Angeles Angels": "LAA",
    "Pittsburgh Pirates": "PIT",
    "Minnesota Twins": "MIN",
    "Washington Nationals": "WSH",
    "Chicago White Sox": "CHW",
    "Colorado Rockies": "COL"
}

#Applies mapping
br_df["Team"] = br_df["Team Name"].map(team_map)
display(br_df)

    Rank              Team Name  Wins  Losses  Runs Allowed Team
0      1      Milwaukee Brewers    97      65           3.9  MIL
1      2  Philadelphia Phillies    96      66           4.0  PHI
2      3      Toronto Blue Jays    94      68           4.5  TOR
3      4       New York Yankees    94      68           4.2  NYY
4      5    Los Angeles Dodgers    93      69           4.2  LAD
5      6           Chicago Cubs    92      70           4.0  CHC
6      7       Seattle Mariners    90      72           4.3  SEA
7      8       San Diego Padres    90      72           3.8   SD
8      9         Boston Red Sox    89      73           4.2  BOS
9     10    Cleveland Guardians    88      74           4.0  CLE
10    11         Houston Astros    87      75           4.1  HOU
11    12         Detroit Tigers    87      75           4.3  DET
12    13          New York Mets    83      79           4.4  NYM
13    14        Cincinnati Reds    83      79           4.2  CIN
14    15     Kansas City Royals    82      80           3.9   KC
15    16   San Francisco Giants    81      81           4.2   SF
16    17          Texas Rangers    81      81           3.7  TEX
17    18   Arizona Diamondbacks    80      82           4.8  ARI
18    19          Miami Marlins    79      83           4.9  MIA
19    20    St. Louis Cardinals    78      84           4.7  STL
20    21         Tampa Bay Rays    77      85           4.2   TB
21    22              Athletics    76      86           5.0  ATH
22    23         Atlanta Braves    76      86           4.5  ATL
23    24      Baltimore Orioles    75      87           4.9  BAL
24    25     Los Angeles Angels    72      90           5.2  LAA
25    26     Pittsburgh Pirates    71      91           4.0  PIT
26    27        Minnesota Twins    70      92           4.8  MIN
27    28   Washington Nationals    66      96           5.5  WSH
28    29      Chicago White Sox    60     102           4.6  CHW
29    30       Colorado Rockies    43     119           6.3  COL

In [28]:
#Merges dataframes
merged_df = pd.merge(br_df, spotrac_cleaned, on="Team", how="inner")

print(merged_df.shape)
display(merged_df)

(30, 8)

,Rank,Team Name,Wins,Losses,Runs Allowed,Team,Active,Total Cash
0,1,Milwaukee Brewers,97,65,3.9,MIL,84095680.0,140266827.0
1,2,Philadelphia Phillies,96,66,4.0,PHI,226300409.0,308208429.0
2,3,Toronto Blue Jays,94,68,4.5,TOR,179210208.0,290944111.0
3,4,New York Yankees,94,68,4.2,NYY,205097386.0,323561450.0
4,5,Los Angeles Dodgers,93,69,4.2,LAD,293126821.0,393082178.0
5,6,Chicago Cubs,92,70,4.0,CHC,173037007.0,231356720.0
6,7,Seattle Mariners,90,72,4.3,SEA,131472218.0,193414894.0
7,8,San Diego Padres,90,72,3.8,SD,160473830.0,236031133.0
8,9,Boston Red Sox,89,73,4.2,BOS,122765355.0,229129601.0
9,10,Cleveland Guardians,88,74,4.0,CLE,50354620.0,118369450.0
10,11,Houston Astros,87,75,4.1,HOU,135180023.0,253425770.0
11,12,Detroit Tigers,87,75,4.3,DET,106720780.0,178924844.0
12,13,New York Mets,83,79,4.4,NYM,312899806.0,400965292.0
13,14,Cincinnati Reds,83,79,4.2,CIN,81066742.0,135790853.0
14,15,Kansas City Royals,82,80,3.9,KC,85396877.0,153094633.0
15,16,San Francisco Giants,81,81,4.2,SF,142688005.0,200678481.0
16,17,Texas Rangers,81,81,3.7,TEX,113977024.0,251697316.0
17,18,Arizona Diamondbacks,80,82,4.8,ARI,73085886.0,204349736.0
18,19,Miami Marlins,79,83,4.9,MIA,33912751.0,90652027.0
19,20,St. Louis Cardinals,78,84,4.7,STL,85089836.0,153377987.0
20,21,Tampa Bay Rays,77,85,4.2,TB,41355049.0,102798243.0
21,22,Athletics,76,86,5.0,ATH,64911684.0,113857137.0
22,23,Atlanta Braves,76,86,4.5,ATL,128648209.0,237076106.0
23,24,Baltimore Orioles,75,87,4.9,BAL,64226457.0,196376385.0
24,25,Los Angeles Angels,72,90,5.2,LAA,97348952.0,230062125.0
25,26,Pittsburgh Pirates,71,91,4.0,PIT,51549367.0,104739138.0
26,27,Minnesota Twins,70,92,4.8,MIN,49208783.0,150415875.0
27,28,Washington Nationals,66,96,5.5,WSH,25294554.0,149257229.0
28,29,Chicago White Sox,60,102,4.6,CHW,17295751.0,101146763.0
29,30,Colorado Rockies,43,119,6.3,COL,60303466.0,149531167.0

In [30]:
#Moves columns for better readability
merged_df = merged_df[["Team", "Team Name", "Rank","Wins","Losses","Runs Allowed","Active","Total Cash"]]
display(merged_df.head())

,Team,Team Name,Rank,Wins,Losses,Runs Allowed,Active,Total Cash
0,MIL,Milwaukee Brewers,1,97,65,3.9,84095680.0,140266827.0
1,PHI,Philadelphia Phillies,2,96,66,4.0,226300409.0,308208429.0
2,TOR,Toronto Blue Jays,3,94,68,4.5,179210208.0,290944111.0
3,NYY,New York Yankees,4,94,68,4.2,205097386.0,323561450.0
4,LAD,Los Angeles Dodgers,5,93,69,4.2,293126821.0,393082178.0

In [32]:
#Saves as csv for my analysis notebook
merged_df.to_csv("salary_analysis_merged_df.csv")